### ISSUE TITLE
Analogue Pocket support?

### ISSUE THREAD

**Issue by Michael-Prince-Sharpe** [nukeykt/Nuked-MD-FPGA#9]
Just a query, I was wondering if the Analogue pocket would be able to support this amazing Mega Drive core?

**Comment by Toryalai1** [comment]
This is not the correct repo to open up a ticket like this. It is better to ask an analogue pocket dev instead

**Comment by atrac17** [comment]
> This is not the correct repo to open up a ticket like this. It is better to ask an analogue pocket dev instead

Don't you have a developer pocket? Maybe it is the right place.

**Comment by ogamespec** [comment]
I just want to remind you that the project is based on reverse-engineering of chips. According to the law, reverse-engineering chips can only be used for home and educational purposes ("fair use"). But if you use it in commercial products, you risk getting a DMCA strike on your product from SEGA.

**Comment by ogamespec** [comment]
@birdybro, explain this to SEGA.

**Comment by birdybro** [comment]
I don't have to, this isn't a company using the chip decaps in their platform. Currently the official analogue cores and systems are already based on reverse engineering in ways that are assumed (at least under US jurisprudence, where the company is based) to be covered by decades of precedent, but even then all emulators potentially are DMCA-able, even ones that aren't in for-profit products.

**Comment by agg23** [comment]
We've discussed this core a bit internally, though I haven't personally looked at porting it. The resource requirements and large build time may cause difficulties, though if you can make it fit, it should be an extremely easy port since the design is not "fully integrated" with the MiSTer APIs (much of my trouble was in dealing with edge cases that MiSTer has and were used in the core, but were not obvious to me).

----

On the concept of the licensing. I will point out that it is extremely likely that you are not using an open source computer to write this post, and thus any such code you run on it is running on a "commercial product". MiSTer is a commercial product if you are using the DE-10 Nano, and it is anyway as it's using an Intel FPGA.

If a large corporation comes after small OSS projects like this, ultimately there's nothing we can do about it, but running this core on an Analogue Pocket will not be the catalyst.

**Comment by sorgelig** [comment]
> MiSTer is a commercial product

MiSTer is not commercial product. It's like calling Linux (or any other free software) as a commercial product because it's running on PC which you have to buy.

**Comment by agg23** [comment]
Yes, I understand that. I was pointing out the ridiculousness of the argument.

**Comment by SegaSnatcher** [comment]
> @birdybro, explain this to SEGA.

Basing your core on decapped chip dies does not change the laws of being allowed to make ports.   

If someone can port cores to the DE-10 Nano then they can port it to the Pocket as well.  

The only issue would be if Analogue themselves released hardware using open source cores, but they don't as all their cores are developed in house.  Giving the ability for third parties to port for their own use is 100% legal and would fall under "home and educational" purposes.

**Comment by birdybro** [comment]
@Michael-Prince-Sharpe - You can probably close this issue as it's not relevant to this repository. Anyone can fork the source code themselves and attempt to port it to any platform they like (as long as they abide by the rules of the GPL2 license).
